rateguru/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$',views.home,name='home'),
    url(r'^give_feedback/(?P<prid>[0-9]+)/$', views.give_feedback, name='give_feedback'),
    url(r'^give_rating/(?P<prid>[0-9]+)/$', views.give_rating, name='give_rating'),
    url(r'^addprof$',views.addprof, name='addprof'),
    url(r'^addcourse$',views.addcourse,name='addcourse'),
    url(r'^allprof$',views.allprof,name='allprof'),
    url(r'^prof_detail/(?P<prid>[0-9]+)/$',views.prof_detail,name='prof_detail'),
    url(r'^add_course$',views.add_course,name='add_course'),
    url(r'^subscribe/(?P<cid>[0-9]+)/$',views.subscribe,name='subscribe'),
    url(r'^student_detail/(?P<stid>[0-9]+)/$',views.student_detail,name='student_detail'),
    url(r'^addquestion$',views.addquestion,name='addquestion'),
    url(r'^form$',views.form,name='form'),
]

rateguru/rateguru/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rateguru.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$' , 'django_cas.views.login'),
    url(r'^accounts/logout' ,'django_cas.views.logout'),
    )

rateguru/main/models.py
from django.db import models
#from django.forms import ModelForm
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
# Create your models here.
class Courses(models.Model):
	Name = models.CharField(max_length=20)
	semester = models.IntegerField()

class Prof(models.Model):
	prof_name = models.CharField(max_length=200)
	email = models.EmailField()
	clarity = models.FloatField(default=0)
	helpfullness = models.FloatField(default=0)
	friendly = models.FloatField(default=0)
	dedicated = models.FloatField(default=0)
	noofratings = models.IntegerField(default=0)
	courses = models.ManyToManyField(Courses)

class Rating(models.Model):
	proff = models.ForeignKey(Prof)
	clarity = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
	helpfullness = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
	friendly = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
	dedicated = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])

class Student(models.Model):
	email = models.EmailField()
	name = models.CharField(max_length=50)
	courses = models.ManyToManyField(Courses)


class Comments(models.Model):
	prof_id = models.ForeignKey(Prof)
	description = models.CharField(max_length=200)
	helpfulness = models.IntegerField()


class Feedback(models.Model):
	proff = models.ForeignKey(Prof)
	choice1 = models.IntegerField()
	choice2 = models.IntegerField()
class PQuestion(models.Model):
	question_text = models.CharField(max_length=200)

#class FeedbackForm(ModelForm):
#	 name = forms.CharField(max_length=100)
#	 title = forms.CharField(max_length=3,widget=forms.Select(choices=TITLE_CHOICES))
#	 birth_date = forms.DateField(required=False)

rateguru/main/forms.py
from django import forms
from .models import PQuestion

class FeedbackForm(forms.Form):
	MY_CHOICES = ((1, '1'),(2, '2'),(3, '3'),(4, '4'),(5, '5'),)
	P=PQuestion.objects.all()
	arr=[]
	for i in P:
		arr.append(i.question_text)
	q1 = forms.ChoiceField(widget=forms.RadioSelect, choices=MY_CHOICES,required=True, label=arr[0])
	q2 = forms.ChoiceField(widget=forms.RadioSelect, choices=MY_CHOICES,required=True, label=arr[1])
	q3 = forms.ChoiceField(widget=forms.RadioSelect, choices=MY_CHOICES,required=True, label=arr[2])
	q4 = forms.ChoiceField(widget=forms.RadioSelect, choices=MY_CHOICES,required=True, label=arr[3])

class RatingForm(forms.Form):
	MY_CHOICES = ((1, '1'),(2, '2'),(3, '3'),(4, '4'),(5, '5'),)
	clarity = forms.ChoiceField(widget=forms.RadioSelect,choices=MY_CHOICES,required=True)
	friendly = forms.ChoiceField(widget=forms.RadioSelect,choices=MY_CHOICES,required=True)
	helpfullness = forms.ChoiceField(widget=forms.RadioSelect,choices=MY_CHOICES,required=True)
	dedicated = forms.ChoiceField(widget=forms.RadioSelect,choices=MY_CHOICES,required=True)


class AddProfForm(forms.Form):
	prof_name = forms.CharField(max_length=200)
	clarity = forms.FloatField()
	helpfullness = forms.FloatField()
	friendly = forms.FloatField()
	dedicated = forms.FloatField()
	noofratings = forms.IntegerField()

class AddCourseForm(forms.Form):
	Name = forms.CharField(max_length=20)
	semester = forms.IntegerField()
class AddPquestionForm(forms.Form):
	question_text = forms.CharField(max_length=100)

  

rateguru/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import FeedbackForm,AddProfForm,AddCourseForm,AddPquestionForm
from .forms import RatingForm,FeedbackForm,AddProfForm,AddCourseForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .models import Feedback,Prof,Courses,Student,PQuestion
from .models import Rating,Feedback,Prof,Courses,Student
from django.core.urlresolvers import reverse
# Create your views here.

def index(request):
	user = User.objects.get(pk=request.user.id)
	print user.username
	return render(request,'main/index.html',{'message':"Website is under construction!",'user' : user})

def give_feedback(request,prid):
	prof = Prof.objects.get(pk=prid)
	if request.method == 'POST':
		form = FeedbackForm(request.POST)
		if form.is_valid():
			q1 = form.cleaned_data['q1']
			q2 = form.cleaned_data['q2']
			q3 = form.cleaned_data['q3']
			q4 = form.cleaned_data['q4']
			feed_obj = Feedback(proff=prof,choice1=q1,choice2=q2)
			feed_obj.save()
			return HttpResponseRedirect(reverse('main:prof_detail', args=(prof.id,)))
	else:
		form = FeedbackForm()
	return render(request,'main/give_feedback.html',{'form':form,'prof':prof})

def allprof(request):
	prof = Prof.objects.all()
	return render(request,'main/allprof.html',{'prof':prof})



def give_rating(request,prid):
	prof = Prof.objects.get(pk=prid)
	if request.method == 'POST':
		form = RatingForm(request.POST)
		if form.is_valid():
			clarity = form.cleaned_data['clarity']
			dedicated = form.cleaned_data['dedicated']
			friendly = form.cleaned_data['friendly']
			helpfullness = form.cleaned_data['helpfullness']
			prof.clarity = (prof.clarity*prof.noofratings+int(clarity))/(prof.noofratings+1)
			prof.friendly = (prof.friendly*prof.noofratings+int(friendly))/(prof.noofratings+1)
			prof.dedicated = (prof.dedicated*prof.noofratings+int(dedicated))/(prof.noofratings+1)
			prof.helpfullness = (prof.helpfullness*prof.noofratings+int(helpfullness))/(prof.noofratings+1)
			prof.noofratings = prof.noofratings + 1
			prof.save()
			feed_obj = Rating(proff=prof,clarity=clarity,dedicated=dedicated,friendly=friendly,helpfullness=helpfullness)
			feed_obj.save()
			return HttpResponseRedirect(reverse('main:prof_detail', args=(prof.id,)))
	else:
		form = RatingForm()
	return render(request,'main/give_rating.html',{'form':form,'prof':prof})

@login_required(login_url='accounts/login')
def home(request):
	user = User.objects.get(pk=request.user.id)
	list = ['students','research']
	#list=[]
	if any(word in user.username for word in list):
		num = Student.objects.filter(email = user.username).count()
		if num==0:
			a = user.username.split('@')
			prof_obj = Student(name=a[0],email=user.username)
			prof_obj.save()
		prof = Student.objects.get(email=user.username)
		return HttpResponseRedirect(reverse('main:student_detail', args=(prof.id,)))
	else:
		num = Prof.objects.filter(email = user.username).count()
		if num==0:
			a = user.username.split('@')
			prof_obj = Prof(prof_name=a[0],email=user.username)
			prof_obj.save()
		prof = Prof.objects.get(email=user.username)
		return HttpResponseRedirect(reverse('main:prof_detail', args=(prof.id,)))


@login_required
def student_detail(request,stid):
	student = Student.objects.get(pk=stid)
	courses = student.courses.all()
	return render(request,'main/student_detail.html',{'student':student,'courses':courses})


def addprof(request):
	if request.method == 'POST':
		form = AddProfForm(request.POST)
		if form.is_valid():
			prof_name = form.cleaned_data['prof_name']
			clarity = form.cleaned_data['clarity']
			helpfullness = form.cleaned_data['helpfullness']
			friendly = form.cleaned_data['friendly']
			dedicated = form.cleaned_data['dedicated']
			noofratings = form.cleaned_data['noofratings']
			prof_obj = Prof(prof_name=prof_name,
				clarity=clarity,
				helpfullness=helpfullness,
				friendly=friendly,
				dedicated=dedicated,
				noofratings=noofratings,
				)
			prof_obj.save()
			return HttpResponse('Prof Created')
	else:
		form = AddProfForm()
	return render(request,'main/addprof.html',{'form':form})
def addcourse(request):
	if request.method == 'POST':
		form = AddCourseForm(request.POST)
		if form.is_valid():
			Course_name = form.cleaned_data['Name']
			semester = form.cleaned_data['semester']
			Course_obj = Courses(Name=Course_name,
						semester=semester,
				)
			Course_obj.save()
			return HttpResponse('Course Created')
	else:
		form = AddCourseForm()
	return render(request,'main/addcourse.html',{'form':form})

def prof_detail(request,prid):
	prof = Prof.objects.get(pk=prid)
	feedback = Feedback.objects.filter(proff=prof)
	rating = Rating.objects.filter(proff=prof)
	print feedback
	return render(request,'main/prof_detail.html',{'prof':prof,'feedback':feedback,'rating':rating})

@login_required
def add_course(request):
	courses= Courses.objects.all()
	return render(request,'main/add_course.html',{'courses':courses})
@login_required
def subscribe(request,cid):
	course=Courses.objects.get(pk=cid)
	student = Student.objects.get(email=request.user.username)
	student.courses.add(course)
	return render(request,'main/subscribe.html',{'message' : "subscibed"})
def addquestion(request):
	if request.method == 'POST':
		form = AddPquestionForm(request.POST)
		if form.is_valid():
			text = form.cleaned_data['question_text']
			que_obj = PQuestion(question_text=text)
			que_obj.save()
			return HttpResponse('Question Added')
	else:
		form = AddPquestionForm()
	return render(request,'main/addquestion.html',{'form':form,})	
def form(request):
	if request.method == 'POST':
		print request.POST.get('country')
		return HttpResponse('Feedback Recieved.')

	return render(request,'main/form.html')
#def prof_profile(request):

rateguru/main/templates/main/add_course.html
{% for course in courses %}
<a href="{% url 'main:subscribe' course.id %}">{{ course.Name }}</a>
</br>
{% endfor %}

rateguru/main/templates/main/addcourse.html
<form action="/main/addcourse" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <br>
    <input type="submit" value="Submit" />
</form>

rateguru/main/templates/main/addprof.html
<form action="/main/addprof" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <br>
    <input type="submit" value="Submit" />
</form>

rateguru/main/templates/main/addquestion.html
<form action="/main/addquestion" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <br>
    <input type="submit" value="Submit" />
</form>

rateguru/main/templates/main/allprof.html
{% for i in prof %}
<h2>{{ i.name }}</h2>
<h2>{{i.email}}</h2>
<a href="{% url 'main:prof_detail' i.id %}">View Profile</a>
</br>
{% endfor %}

rateguru/main/templates/main/form.html
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Feedback Form</title>
		<meta name="keywords" content="responsive form, inputs, html5, responsive, multi-column, fluid, media query, template" />
		<meta name="author" content="Codrops" />
		<link rel="shortcut icon" href="../favicon.ico">
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/default.css" />
		<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/component.css" />
		<script src="{{STATIC_URL}}js/modernizr.custom.js"></script>
	</head>
	<body>
		<div class="container">
			<header class="clearfix">
				<span>Blueprint <span class="bp-icon bp-icon-about" data-content="The Blueprints are a collection of basic and minimal website concepts, components, plugins and layouts with minimal style for easy adaption and usage, or simply for inspiration."></span></span>
				<h1>Feedback</h1>
			</header>	
			<div class="main">
				<form class="cbp-mc-form" method="post">
					{% csrf_token %}
					<div class="cbp-mc-column">
						<label for="first_name">First Name</label>
	  					<input type="text" id="first_name" name="first_name" placeholder="Jonathan">
	  					<label for="last_name">Last Name</label>
	  					<input type="text" id="last_name" name="last_name" placeholder="Doe">
	  					<label for="email">Email Address</label>
	  					<input type="text" id="email" name="email" placeholder="jon@doe.com">
	  					<label for="country">Country</label>
	  					<select id="country" name="country">
	  						<option>Choose a country</option>
	  						<option>France</option>
	  						<option>Italy</option>
	  						<option>Portugal</option>
	  					</select>
	  					<label for="bio">Biography</label>
	  					<textarea id="bio" name="bio"></textarea>
	  				</div>
	  				<div class="cbp-mc-column">
	  					<label for="phone">Phone Number</label>
	  					<input type="text" id="phone" name="phone" placeholder="+351 999 999">
						<label for="affiliations">Affiliations</label>
	  					<textarea id="affiliations" name="affiliations"></textarea>
	  					<label>Occupation</label>
	  					<select id="occupation" name="occupation">
	  						<option>Choose an occupation</option>
	  						<option>Web Designer</option>
	  						<option>Web Developer</option>
	  						<option>Hybrid</option>
	  					</select>
	  					<label for="cat_name">Cat's name</label>
	  					<input type="text" id="cat_name" name="cat_name" placeholder="Kitty">
	  					<label for="gagdet">Favorite Gadget</label>
	  					<input type="text" id="gagdet" name="gagdet" placeholder="Annoy-a-tron">
	  				</div>
	  				<div class="cbp-mc-column">
	  					<label>Type of Talent</label>
	  					<select id="talent" name="talent">
	  						<option>Choose a talent</option>
	  						<option>Ninja silence</option>
	  						<option>Sumo power</option>
	  						<option>Samurai precision</option>
	  					</select>
						<label for="drink">Favorite Drink</label>
	  					<input type="text" id="drink" name="drink" placeholder="Green Tea">
	  					<label for="power">Special power</label>
	  					<input type="text" id="power" name="power" placeholder="Anti-gravity">
	  					<label for="weapon">Weapon of choice</label>
	  					<input type="weapon" id="weapon" name="weapon" placeholder="Lightsaber">
	  					<label for="comments">Comments</label>
	  					<textarea id="comments" name="comments"></textarea>	
	  				</div>
	  				<div class="cbp-mc-submit-wrap"><input class="cbp-mc-submit" type="submit" value="Send your data" /></div>
				</form>
			</div>
		</div>
	</body>
</html>

rateguru/main/templates/main/give_feedback.html
<form action="/main/give_feedback" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <br>
    <input type="submit" value="Submit" />
</form>

rateguru/main/templates/main/give_rating.html
<form action="{% url 'main:give_rating' prof.id %}" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <br>
    <input type="submit" value="Submit" />
</form>

rateguru/main/templates/main/index.html
<h3> {{ message }} </h3>
<h3> {{ user.name }} </h3>

rateguru/main/templates/main/prof_detail.html
<h3>{{prof.prof_name}}</h3>
<a href="{% url 'main:give_feedback' prof.id %}">Give Feedback</a>
</br>
<a href="{% url 'main:give_rating' prof.id %}">Give Rating</a>




<h2> Dedication: {{prof.dedicated}}</h2>
<h2> Clarity: {{prof.clarity}}</h2>
<h2> Friendliness: {{ prof.friendly }}</h2>
<h2> Helpfulness: {{prof.helpfullness}}</h2>
</br>

rateguru/main/templates/main/student_detail.html
<h3>{{student.name}}</h3>
<a href="{% url 'main:add_course' %}">Subscribe Courses</a>
</br>
<h2> Subscribed Courses </h2>
{% for course in courses	 %}
<h3>{{ course.Name }}</h3>
{% endfor %}
</br>
<a href="{% url 'main:allprof' %}">View all professors</a>
</br>
<a href="{% url 'django_cas.views.logout' %}">Log out</a>

rateguru/main/templates/main/subscribe.html
{{message}}

rateguru/main/templates/main/userhome.html
{% for prof in all_prof %}
<a href="{% url 'main:prof_detail' prof.id %}">{{ prof.prof_name }}</a>
{% endfor %}